### ISSUE TITLE
SSH not working when container runs as non-root in Kubernetes

### ISSUE THREAD

**Issue by tuxpeople** [Kaiede/Bedrockifier#82]
While working on getting the container working on Kubernetes (as mentioned here https://github.com/itzg/docker-minecraft-bedrock-server/issues/86) I faced following issue:

Bedrockifier wasn't able to open the SSH connection to the Bedrock container. When trying it manually, I got the following error:

```
No user exists for uid 1000
```

I then tried it with a modified image like this:

```Dockerfile
FROM kaiede/minecraft-bedrock-backup:latest
RUN adduser --uid 1000 bedrockifier
```

This worked. I can see you have logic to add a user in `entry.sh`:

https://github.com/Kaiede/Bedrockifier/blob/8af09d05bf217e5e2bc8ab5d6869cde6ab2b6e41/Docker/entry.sh#L8-L12

This cannot work if the container is not running as root. Not only in my use case, I assume also in rootless Docker installations and Podman environments. If you'd like a better solution than my Dockerfile above, I would suggest to add this line to the Dockerfile:

https://github.com/Kaiede/Bedrockifier/blob/8af09d05bf217e5e2bc8ab5d6869cde6ab2b6e41/Docker/entry.sh#L11

In most cases, if not all cases, it should be possible to fix the permissions on the storage end. You could still leave the part in the entry.sh and wrap it into a `if` condition to check whether or not the container runs as root. 

I'll open a "minimal solution" PR to "fix" this. However, I'm open for a more sophisticated solution like described above.

**Comment by Kaiede** [comment]
Neither approach is a complete fix, as SSH needs a valid user for whatever UID it picks up when it is started. Because of how the entry point demotes the service down to whatever user owns the backups folder, it's going to pick up the UID of that owner, which can be pretty much anything. Even with root disabled, there's no guarantee that the UID is what would be configured in the Dockerfile. 

For example:
- If I'm not the first user on a system.
- If I'm on a system where UIDs for regular users start at different values (Mac using Docker Desktop). 
- If I give ownership of the backups to a service account for off-site uploads or the like.

Bringing the line into the Dockerfile uses the docker build environment, rather than the actual runtime environment, so I'm not sure how that's a better solution? 

The "best" solution is to bring the SSH functionality in-process where we aren't having to deal with the environment when all we want is a secure pipe. And this is something I've been playing with locally, but it isn't remotely ready yet. Partly because there's multiple prototypes I'm playing with: using SwiftNIO's SSH functionality, using Golang for the whole service (saves a bunch of space, potentially fixes Windows bugs), and using Golang for a "dialer" tool that replaces rcon-cli/ssh/docker-cli in the container.

**Comment by Kaiede** [comment]
I do just want to say thanks for opening the issue. This is a good catch.

**Comment by tuxpeople** [comment]
I discovered that (at least in my case) it also works without specifying a specific id:

```Dockerfile
FROM kaiede/minecraft-bedrock-backup:latest
RUN adduser bedrockifier
```

Docker users may use the `--user` parameter (https://docs.docker.com/engine/reference/run/#user) to specify a specific userid? I have something similar in Kubernetes (https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod). However, I didn't had the time to test what happens if I use it, as it would have also implications on the Bedrock container in my setup. But it will still need a username for SSH.

Having users in Dockerfiles is not unusual. Instead , it's considered best practice. While I was searching for I reference for this, I came across this: https://sysdig.com/blog/dockerfile-best-practices/#1 and found out that using a specific user id is something I should have avoided. Therefore I suggest to drop the user id :-) sorry about that!

**Comment by Kaiede** [comment]
> Having users in Dockerfiles is not unusual. Instead , it's considered best practice.

Don’t disagree, but it’s so much easier when services aren’t having to reach across into other services’ volumes. Or when not dealing with _interesting_ setups that entrypoint-demoter was built to solve: https://github.com/itzg/entrypoint-demoter, such as when `--user` doesn’t play nice with attached volumes like Synology’s setup. 

But ultimately, the only reason this specific account is even needed is because the SSH CLI demands the UID it is started with be a real user _inside the container_. So what UID ‘bedrockifier’ gets during container creation still needs to match the UID of the process when it is later run. It’s… not fun.

With this in mind, I still think the more appropriate long-term fix is to ditch the SSH CLI and use the underlying library instead. It removes the whole requirement of a “real user” from SSH.

**Comment by tuxpeople** [comment]
> With this in mind, I still think the more appropriate long-term fix is to ditch the SSH CLI and use the underlying library instead. It removes the whole requirement of a “real user” from SSH.

I'm fine with that, but sounds like a lot of work for you, I'm afraid. I can work with my customized image for the time being. It gets rebuilt automatically with the latest version of your image (btw. would you be open to versioning your images instead of using only `latest`?).

**Comment by Kaiede** [comment]
> sounds like a lot of work for you, I'm afraid.

Depends. Managing PTYs to use client apps rather than libraries is always a pain and introduces overhead. Moving to a library pays down that technical debt and makes things cheaper to maintain. The SSH client in particular is hostile to automation (for good reason though), so it's an even bigger pain to work with than the docker CLI tool. 

As mentioned earlier in the thread, I have been looking at what the future looks like in a couple ways, as Swift isn't exactly the easiest to work with for a tool like this (lack of good networking packages for non-HTTP things, really, which is why there is PTY hell instead). 

> would you be open to versioning your images instead of using only latest?

This is something I've been kicking around, but just haven't updated the Github workflows to do it yet. Backwards compatibility with previous behaviors hasn't been an issue (yet).

**Comment by Kaiede** [comment]
Just wanted to add a progress update here on this, as I am done prototyping things.

I've demonstrated to myself that I can integrate an SSH client into the service as-is without much trouble. That's good. Even better, SwiftNIO is built such that I should be able to directly attach the input/output of the SSH channel to the "Terminal" object I use which handles all the read/write and expectations that handle automating communication with the container. That makes it even better. 

mc-server-runner will also need changes though. SwiftNIO's SSH client doesn't currently support RSA, just ECDSA. I've made some changes to mc-server-runner that makes it generate and use both keys for compatibility. There's a bug before I can open a PR against the project though, as it doesn't fully handle backwards compatibility with the old host keys properly which needs to be done properly.

The catch is that this will introduce a breaking change, as the new SSH client won't support the current mc-server-runner, but if this is the worst of it, that's fine.

**Comment by Kaiede** [comment]
Pulled the PR for mc-server-runner changes needed as I got some time this weekend to address the backwards compatibility. Will need to wait for this to filter through to the Bedrock and Java server containers.

I've also got an early branch with the changes needed for Bedrockifier, but the error reporting for the integrated SSH client needs some work, and I need to do some testing of the end-to-end to ensure it all works as expected.

**Comment by Kaiede** [comment]
Managed to get the end-to-end working now that the mc-server-runner changes are merged and the java/bedrock servers have been updated to include them.

Things are actually looking pretty good right now. Backup worked as expected first try, commands were sent and received over the SSH pipe and that all worked quite cleanly. There’s a couple bugs that I need to address, related to the PTY used by the SSH client, before the changes are ready to make a PR for.

**Comment by Kaiede** [comment]
I’ve been running some long-term testing, but things have been a bit busy with the day job, and I’ve had to step back from a couple things to avoid burn out. Things are looking generally good as I’ve been getting reliable backups over the last month with our primary server though, although I’ve hit a couple issues I want to fix, and there’s still one missing bit of functionality:

1) Connection errors from the network library I’m using aren’t terribly helpful for diagnostics when logged. ‘ChannelError error 9’ rather than ‘password was rejected’ for example.
2) When using `passwordFile`, which people _should_, if the server reboots for any reason the backup service will refuse to pick up the new password that was generated until it is also rebooted. This is an existing bug, but I’d like to fix it now.
3) Right now the backup service accepts all host keys. I want it to remember host keys it’s seen and (by default) error when a host key unexpectedly changes. 

Not a lot of work here, so I’ll see if I can get to it soon. As work is now back into a normal rhythm, it will be a bit easier. Let me see what I can get done this week.

**Comment by Kaiede** [comment]
The integrated SSH server is now in the test tag and will be in the next release.
